export const BADGE_STATUSES = {
  banned: 'banned',
  active: 'active',
  inactive: 'inactive',
  pending: 'pending',
  paid: 'paid',
  expired: 'expired',
  new: 'new',
  rejected: 'rejected',
  default: 'new',
  processed: 'done',
  authorized: 'authorized',
  approved: 'approved',
  declined: 'declined',
  activated: 'activated',
  stopped: 'stopped',
  deactivate: 'deactivate',
  deactivated: 'deactivated',
  done: 'processed',
  none: 'none',
};
