import type { ITableFilter } from '@sdk5/shared/types';

export const transactionsFilters: ITableFilter[] = [
  {
    type: 'Enumeration',
    name: 'filter.status',
    param: 'statuses',
    label: 'filter.status',
    options: {
      pending: 'entity.transaction.status.pending',
      declined: 'entity.transaction.status.declined',
      processed: 'entity.transaction.status.processed',
      error: 'entity.transaction.status.error',
      rejected: 'entity.transaction.status.rejected',
    },
  },
  {
    type: 'Enumeration',
    name: 'filter.types',
    param: 'types',
    label: 'filter.types',
    options: {
      client_transaction_transfer: 'entity.transaction.type.client_transaction_transfer',
      client_transaction_issue: 'entity.transaction.type.client_transaction_issue',
      client_create_prepaid: 'entity.transaction.type.client_create_prepaid',
      client_charge_prepaid: 'entity.transaction.type.client_charge_prepaid',
      merchant_payment: 'entity.transaction.type.merchant_payment',
      merchant_invoice: 'entity.transaction.type.merchant_invoice',
      gate_charge: 'entity.transaction.type.gate_charge',
      gate_redeem: 'entity.transaction.type.gate_redeem',
      gate_purchase: 'entity.transaction.type.gate_purchase',
      exchange_transaction: 'entity.transaction.type.exchange_transaction',
      cash_desk_redeem: 'entity.transaction.type.cash_desk_redeem',
      cash_desk_charge: 'entity.transaction.type.cash_desk_charge',
      cash_investment: 'entity.transaction.type.cash_investment',
      cash_collect: 'entity.transaction.type.cash_collect',
      cash_input: 'entity.transaction.type.cash_input',
      contract_transit: 'entity.transaction.type.contract_transit',
      bank_topup: 'entity.transaction.type.bank_topup',
      bank_redeem: 'entity.transaction.type.bank_redeem',
      gate_issue_card: 'entity.transaction.type.gate_issue_card',
    },
  },
  {
    type: 'Date',
    name: 'filter.date_from',
    param: 'createdAtFrom',
    label: 'filter.created_at',
    range: {
      type: 'from',
      param: 'createdAtTo',
    },
    placeholder: 'placeholder.input.date_from',
  },
  {
    type: 'Date',
    name: 'filter.date_to',
    param: 'createdAtTo',
    range: {
      type: 'to',
      param: 'createdAtFrom',
    },
    placeholder: 'placeholder.input.date_to',
  },
  {
    type: 'Enumeration',
    name: 'filter.currency_code',
    param: 'currencyCodes',
    label: 'filter.currency_code',
    options: {},
  },
  {
    name: 'filter.wallet_number',
    type: 'Multiple',
    param: 'coinSerials',
    label: 'filter.wallet_number',
  },
  {
    name: 'filter.transaction_id',
    type: 'Multiple',
    param: 'ids',
    folded: true,
    label: 'filter.transaction_id',
  },
  {
    name: 'filter.currency_id',
    type: 'Multiple',
    param: 'currenciesIds',
    folded: true,
    label: 'filter.currency_id',
  },
  {
    name: 'filter.request_identifier',
    type: 'Multiple',
    param: 'requestIdentifiers',
    folded: true,
    label: 'filter.request_identifier',
  },
];
